spring:
  application:
    name: ${APP_NAME:Luto SaaS}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/luto?serverTimezone=UTC}
    username: ${DB_USERNAME:luto}
    password: ${DB_PASSWORD:luto}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: INFO

security:
  jwt:
    issuer: ${JWT_ISSUER:dev-issuer}
    public-key: ${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----\nREPLACE\n-----END PUBLIC KEY-----}

S3_ENDPOINT: ${S3_ENDPOINT:http://localhost:9000}
S3_ACCESS_KEY: ${S3_ACCESS_KEY:minioadmin}
S3_SECRET_KEY: ${S3_SECRET_KEY:minioadmin}
S3_BUCKET: ${S3_BUCKET:luto-evidencias}
S3_OBJECT_LOCK_ENABLED: ${S3_OBJECT_LOCK_ENABLED:true}

WEBHOOK_SECRET: ${WEBHOOK_SECRET:dev-secret}

cielo:
  sftp:
    host: ${CIELO_SFTP_HOST:localhost}
    port: ${CIELO_SFTP_PORT:22}
    username: ${CIELO_SFTP_USER:user}
    password: ${CIELO_SFTP_PASSWORD:pass}
    remoteDir: ${CIELO_SFTP_DIR:/edi}
    tenantId: ${CIELO_TENANT_ID:00000000-0000-0000-0000-000000000001}
